apiVersion: v1
kind: Service
metadata:
  name: {{ template "exchangelistener.fullname" . }}
  labels:
    app: {{ template "exchangelistener.name" . }}
    chart: {{ template "exchangelistener.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ template "exchangelistener.name" . }}
    release: {{ .Release.Name }}
  livenessProbe:
    httpGet:
      path: /api/listeners/status
