apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "exchangelistener.fullname" . }}
spec:
  serviceName: {{ template "exchangelistener.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "exchangelistener.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "exchangelistener.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/listeners/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/listeners/status
              port: http
        {{- with .Values.env }}
          env:
            - name: PodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{ toYaml . | indent 12  }}
          {{ end }}
        {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
